using System.Reflection;

namespace Caldera.Cli.Generation;

public static class Metadata {
    public static string GetPrologueString(string version) {
        return $"""
                // <auto-generated>
                //   This code was generated by Caldera.
                //   Caldera Version: {version}
                //
                //   Report issues to https://github.com/glomdom/Caldera
                // </auto-generated>

                using System.CodeDom.Compiler;
                using System.Runtime.InteropServices;

                namespace Caldera;
                """;
    }
    
    public static string GetAssemblyVersion() {
        return Assembly.GetEntryAssembly()
                   ?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                   ?.InformationalVersion ??
               throw new InvalidOperationException("Failed to get entry assembly version.");
    }
}