using System.Reflection;
using Spectre.Console;

namespace Caldera.Cli;

public static class Utilities {
    public static string GetPrologueString(string version) {
        return $"""
                // <auto-generated>
                //   This code was generated by Caldera.
                //   Caldera Version: {version}
                //
                //   Report issues to https://github.com/glomdom/Caldera
                // </auto-generated>

                using System.CodeDom.Compiler;

                namespace Caldera;
                """;
    }

    public static void PrintBanner() {
        var lines = Constants.Banner.Split('\n');
        for (var i = 0; i < lines.Length; i++) {
            var ratio = lines.Length > 1 ? (double)i / (lines.Length - 1) : 0;
            var r = (byte)(255 - (255 - 180) * ratio);
            var g = (byte)(165 - (165 - 50) * ratio);

            AnsiConsole.MarkupLine($"[rgb({r},{g},0)]{lines[i]}[/]");
        }

        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine("[gray70]A C# Vulkan bindings forge.[/]");
    }

    public static string CleanEnumName(string raw) => raw.StartsWith("Vk") ? raw[2..] : raw;
    public static string CleanEnumValue(string raw) => raw.StartsWith("VK_") ? raw[3..] : raw;
    public static string NormalizeValue(string raw) => raw.Replace("LL", "L");

    public static string GetTypeFromXml(string xmlType) => xmlType switch {
        "uint32_t" => "uint",
        "uint64_t" => "ulong",
        "float" => "float",

        _ => throw new ArgumentOutOfRangeException(nameof(xmlType), xmlType, $"Unrecognized type '{xmlType}'."),
    };

    public static string GetAssemblyVersion() {
        return Assembly.GetEntryAssembly()
                   ?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                   ?.InformationalVersion ??
               throw new InvalidOperationException("Failed to get entry assembly version.");
    }
}