using System.Reflection;

namespace Caldera.Cli;

public static class Utilities {
    public static string GetPrologueString(string version) {
        return $"""
                // <auto-generated>
                //   This code was generated by Caldera.
                //   Caldera Version: {version}
                //
                //   Report issues to https://github.com/glomdom/Caldera
                // </auto-generated>

                using System.CodeDom.Compiler;
                using System.Runtime.InteropServices;

                namespace Caldera;
                """;
    }

    public static string GetTypeFromXml(string xmlType) => xmlType switch {
        "int32_t" => "int",
        "uint8_t" => "byte",
        "uint32_t" => "uint",
        "uint64_t" => "ulong",
        "int64_t" => "long",
        "size_t" => "nuint",
        "float" => "float",
        "void" => "void",

        _ => xmlType,
    };

    public static string GetAssemblyVersion() {
        return Assembly.GetEntryAssembly()
                   ?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                   ?.InformationalVersion ??
               throw new InvalidOperationException("Failed to get entry assembly version.");
    }
}