namespace Caldera.Cli;

public static class Utilities {
    public static string GetPrologueString(string version) {
        return $"""
                // <auto-generated>
                //   This code was generated by Caldera.
                //   Caldera Version: {version}
                //
                //   Report issues to https://github.com/glomdom/Caldera
                // </auto-generated>

                using System.CodeDom.Compiler;

                namespace Caldera;
                """;
    }

    public static string CleanEnumName(string raw) => raw.StartsWith("Vk") ? raw[2..] : raw;
    public static string CleanEnumValue(string raw) => raw.StartsWith("VK_") ? raw[3..] : raw;
    public static string NormalizeValue(string raw) => raw.Replace("LL", "L");

    public static string GetTypeFromXml(string xmlType) => xmlType switch {
        "uint32_t" => "uint",
        "uint64_t" => "ulong",
        "float" => "float",

        _ => throw new ArgumentOutOfRangeException(nameof(xmlType), xmlType, $"Unrecognized type '{xmlType}'."),
    };
}